# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536813c6caa4d4bb710c992744b5d624bc1797be86d08ed9e2ea3cc93bbc2db8b0dd7fa065363f45a3ca68e6fdc82f4c41bda8db8ae598d4f6abb310b918f80f

test:
  secret_key_base: fb60bb97baa65aca071edd4ff3cce7ee1123be1b1dca6fec498550d03bc547dee1cb56b1bd28b53a6d71b4861897e55e18362b84705b38cee07c1106e1191af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
